---
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    post_checkout:
      # Cancel building pull requests when there aren't any changes to the docs folder or mkdocs.yml
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ mkdocs.yml docs-requirements.txt;
        then
          exit 183;
        fi

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  install:
    - requirements: docs-requirements.txt

formats:
  - pdf
  - epub
