---
name: Setup Python Environment
description: Checks out repository, sets up Python, caches pip dependencies, and installs project dependencies.

inputs:
  fetch-depth:
    description: Depth for git checkout
    required: false
    default: '1' # Default to 1 for efficiency, can be overridden to 0 for full history
  python-version:
    description: Python version to use
    required: false
    default: '3.11'
  requirements-file:
    description: Path to the requirements file to install
    required: false
    default: requirements-dev.txt

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Get pip cache dir
      id: pip-cache
      shell: bash
      run: |
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles(inputs.requirements-file) }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements-file }}
