---
name: Git Config and Commit
description: Configures Git user and commits/pushes changes if any are detected.

inputs:
  user-email:
    description: Email for Git commit author
    required: true
  user-name:
    description: Name for Git commit author
    required: true
  commit-message:
    description: Commit message
    required: true
  files-to-add:
    description: Space-separated list of files/patterns to add to git
    required: true
  push-branch:
    description: Branch to push to (e.g., main)
    required: false
    default: ${{ github.ref }}

runs:
  using: composite
  steps:
    - name: Configure Git User
      shell: bash
      run: |
        set -e
        git config --local user.email "${{ inputs.user-email }}"
        git config --local user.name "${{ inputs.user-name }}"

    - name: Add files to Git
      shell: bash
      run: |
        set -e
        git add ${{ inputs.files-to-add }}

    - name: Commit and Push Changes
      shell: bash
      run: |
        set -e
        if ! git diff --staged --quiet; then
          git commit -m "${{ inputs.commit-message }}"
          git push origin ${{ inputs.push-branch }}
        else
          echo "No changes to commit."
        fi
